# Generated by Django 5.0.6 on 2024-07-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_created_at_alter_courses_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='the section number or sequence number')),
                ('title', models.CharField(max_length=150)),
                ('tot_time', models.IntegerField(verbose_name='total time taken to complete the section')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='order number of the chapter in a lesson')),
                ('title', models.CharField(max_length=150)),
                ('time', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.section')),
            ],
            options={
                'verbose_name_plural': 'Chapters',
            },
        ),
    ]
