# Generated by Django 5.0.6 on 2024-07-10 15:40

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(null=True, upload_to='chapter_video_upload_to'),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=courses.models.thumbnail_upload_to),
        ),
    ]
