# Generated by Django 5.0.7 on 2024-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_chapter_video_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
