# Generated by Django 5.0.7 on 2024-07-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_chapter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order number of the chapter in a lesson'),
        ),
    ]
