# Generated by Django 5.0.7 on 2024-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tot_time',
            field=models.IntegerField(null=True, verbose_name='total time taken to complete the section'),
        ),
    ]
