# Generated by Django 5.0.7 on 2024-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_section_tot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
